<?php

namespace Database\Seeders;

use App\Models\Entity\Couple;
use App\Models\Entity\Entity;
use App\Models\Zz\Categories;
use App\Models\Zz\Status;
use Illuminate\Database\Seeder;

class EntitiesSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id'                       => '01HV670JX63VDJAHN7KR34WBC3',
                'name'                     => 'Abd. Majid',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV671S4M6JH0HS1C30BBFNNE',
                'name'                     => 'Rahmah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'gender_id'                => Categories::$GENDER_FEMALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0001',
                'name'                     => 'Sabariah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_FEMALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0002',
                'name'                     => 'Abdullah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0003',
                'name'                     => 'Hashim',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0004',
                'name'                     => 'Abd. Manan',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0005',
                'name'                     => 'Khalid',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0006',
                'name'                     => 'Dahlan',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0007',
                'name'                     => 'Eshak',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => '0',
                'father_id'                => '01HV670JX63VDJAHN7KR34WBC3',
                'mother_id'                => '01HV671S4M6JH0HS1C30BBFNNE',
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJQ0008',
                'name'                     => 'Zainon',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => '0',
                'date_of_death'            => null,
                'is_date_of_death_precise' => '0',
                'gender_id'                => Categories::$GENDER_FEMALE,
                'is_foster'                => '01HV654SNVDSPWA58A1JT60001',
                'foster_father_id'         => '01HV654SNVDSPWA58A1JT60001',
                'foster_mother_id'         => '01HV65XCD59TBTDWGYC9B2S5YD',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0001',
                'name'                     => 'Mamat',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0002',
                'name'                     => 'Zainal',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => '1970-01-01',
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0003',
                'name'                     => 'Zuraidah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0004',
                'name'                     => 'Zaharah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0005',
                'name'                     => 'Zanariah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0006',
                'name'                     => 'Zainuddin',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0007',
                'name'                     => 'Masmera',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0008',
                'name'                     => 'Salleh',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0009',
                'name'                     => 'Rafidah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0009',
                'name'                     => 'Sapura',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJR0010',
                'name'                     => 'Kamal',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJQ0007',
                'mother_id'                => '01HV673A1SQH14AYWRTBJQ0008',
            ],
            [
                'id'                       => '01HV673A1SQH14AYWRTBJS0001',
                'name'                     => 'Latipah',
                'date_of_birth'            => '1970-01-01',
                'is_date_of_birth_precise' => 0,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
            ],

            [
                'id'                       => '01HV654SNVDSPWA58A1JT60001',
                'name'                     => 'Muhammad Syafiq',
                'date_of_birth'            => '1987-12-17',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJR0006',
                'mother_id'                => '01HV673A1SQH14AYWRTBJS0001',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2S5YD',
                'name'                     => 'Sh. Fatimatul Zahrah',
                'date_of_birth'            => '1987-08-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
            ],
            [
                'id'                       => '01HV65XN7VPVYZ0DAM7F6VXEFV',
                'name'                     => 'Muhammad Adam Assyarif',
                'date_of_birth'            => '2014-08-01',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV654SNVDSPWA58A1JT60001',
                'mother_id'                => '01HV65XCD59TBTDWGYC9B2S5YD',
            ],
            [
                'id'                       => '01HV65XV6NGQKMTFBZV4SXENSN',
                'name'                     => 'Rumaisha Mardiyah',
                'date_of_birth'            => '2019-01-26',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV654SNVDSPWA58A1JT60001',
                'mother_id'                => '01HV65XCD59TBTDWGYC9B2S5YD',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2S001',
                'name'                     => 'Ili Syairah',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJR0006',
                'mother_id'                => '01HV673A1SQH14AYWRTBJS0001',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2S006',
                'name'                     => 'Farid',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2T001',
                'name'                     => 'Izz Syakir Zafran',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
                'father_id'                => '01HV65XCD59TBTDWGYC9B2S006',
                'mother_id'                => '01HV65XCD59TBTDWGYC9B2S001',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2T002',
                'name'                     => 'Zafira',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV65XCD59TBTDWGYC9B2S006',
                'mother_id'                => '01HV65XCD59TBTDWGYC9B2S001',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2T003',
                'name'                     => 'Zafrina',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV65XCD59TBTDWGYC9B2S006',
                'mother_id'                => '01HV65XCD59TBTDWGYC9B2S001',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2S002',
                'name'                     => 'Syamin Natasha',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJR0006',
                'mother_id'                => '01HV673A1SQH14AYWRTBJS0001',
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2S007',
                'name'                     => 'Aiman',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_MALE,
            ],
            [
                'id'                       => '01HV65XCD59TBTDWGYC9B2S003',
                'name'                     => 'Nayli Syahmi',
                'date_of_birth'            => '1990-06-29',
                'is_date_of_birth_precise' => 1,
                'date_of_death'            => null,
                'is_date_of_death_precise' => 0,
                'gender_id'                => Categories::$GENDER_FEMALE,
                'father_id'                => '01HV673A1SQH14AYWRTBJR0006',
                'mother_id'                => '01HV673A1SQH14AYWRTBJS0001',
            ],
        ];

        foreach ($data as $datum) {
            Entity::updateOrCreate(['id' => $datum['id']], [
                'name'                     => $datum['name'],
                'date_of_birth'            => $datum['date_of_birth'],
                'is_date_of_birth_precise' => $datum['is_date_of_birth_precise'],
                'gender_id'                => $datum['gender_id'],
                'father_id'                => $datum['father_id'] ?? null,
                'mother_id'                => $datum['mother_id'] ?? null,
                'age'                      => $datum['date_of_death'] == null
                    ? date('Y') - mb_substr($datum['date_of_birth'], 0, 4)
                    : date('Y') - mb_substr($datum['date_of_death'], 0, 4),
            ]);
        }

        $data = [
            [
                'husband_id'        => '01HV673A1SQH14AYWRTBJQ0007',
                'wife_id'           => '01HV673A1SQH14AYWRTBJQ0008',
                'marital_status_id' => Status::$MARTIAL_MARRIED,
                'marriage_date'     => '2013-05-26',
                'divorce_date'      => null,
                'divorce_type_id'   => null,
            ],
            [
                'husband_id'        => '01HV670JX63VDJAHN7KR34WBC3',
                'wife_id'           => '01HV671S4M6JH0HS1C30BBFNNE',
                'marital_status_id' => Status::$MARTIAL_MARRIED,
                'marriage_date'     => '2013-05-26',
                'divorce_date'      => null,
                'divorce_type_id'   => null,
            ],
            [
                'husband_id'        => '01HV654SNVDSPWA58A1JT60001',
                'wife_id'           => '01HV65XCD59TBTDWGYC9B2S5YD',
                'marital_status_id' => Status::$MARTIAL_MARRIED,
                'marriage_date'     => '2013-05-26',
                'divorce_date'      => null,
                'divorce_type_id'   => null,
            ],
            [
                'husband_id'        => '01HV673A1SQH14AYWRTBJR0006',
                'wife_id'           => '01HV673A1SQH14AYWRTBJS0001',
                'marital_status_id' => Status::$MARTIAL_MARRIED,
                'marriage_date'     => '1987-01-10',
                'divorce_date'      => null,
                'divorce_type_id'   => null,
            ],
            [
                'husband_id'        => '01HV65XCD59TBTDWGYC9B2S006',
                'wife_id'           => '01HV65XCD59TBTDWGYC9B2S001',
                'marital_status_id' => Status::$MARTIAL_MARRIED,
                'marriage_date'     => '1970-01-01',
                'divorce_date'      => null,
                'divorce_type_id'   => null,
            ],
            [
                'husband_id'        => '01HV65XCD59TBTDWGYC9B2S007',
                'wife_id'           => '01HV65XCD59TBTDWGYC9B2S002',
                'marital_status_id' => Status::$MARTIAL_MARRIED,
                'marriage_date'     => '1970-01-01',
                'divorce_date'      => null,
                'divorce_type_id'   => null,
            ],
        ];

        foreach ($data as $datum) {
            Couple::updateOrCreate(
                [
                    'husband_id' => $datum['husband_id'],
                    'wife_id'    => $datum['wife_id'],
                ],
                [
                    'marital_status_id' => $datum['marital_status_id'],
                    'marriage_date'     => $datum['marriage_date'],
                    'divorce_date'      => $datum['divorce_date'],
                    'divorce_type_id'   => $datum['divorce_type_id'],
                ]
            );
        }
    }
}
